DROP DATABASE AcademyProject
GO

CREATE DATABASE AcademyProject
GO

USE AcademyProject
GO

CREATE TABLE Pictures
(
	Id INT IDENTITY PRIMARY KEY,
	PicturePath NVARCHAR(255) NOT NULL UNIQUE
)
INSERT INTO Pictures VALUES ('/')

CREATE TABLE Users
(
	Id INT IDENTITY PRIMARY KEY,
	Email NVARCHAR(255) NOT NULL,
	PasswordHash NVARCHAR(255),
	FirstName NVARCHAR(255) NOT NULL,
	LastName NVARCHAR(255) NOT NULL,
	PictureId INT DEFAULT 1,
	FOREIGN KEY (PictureId) REFERENCES Pictures(Id)
)

CREATE TABLE Roles
(
	Id INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(255) NOT NULL
)

CREATE TABLE UserRoles
(
	UserId INT NOT NULL,
	RoleId INT NOT NULL,
	PRIMARY KEY(UserId, RoleId),
	FOREIGN KEY (UserId) REFERENCES Users(Id),
	FOREIGN KEY (RoleId) REFERENCES Roles(Id)
)

CREATE TABLE Category
(
	Id INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(255) NOT NULL
)

CREATE TABLE Blogs
(
	Id INT IDENTITY PRIMARY KEY,
	UserId INT NOT NULL,
	CategoryId INT NOT NULL,
	Title NVARCHAR(255) NOT NULL,
	Content NTEXT NOT NULL,
	CreateAt DATETIME NOT NULL DEFAULT GETDATE(),
	IsDeleted BIT NOT NULL DEFAULT 0, --True xóa
	PictureId INT DEFAULT 1,
	FOREIGN KEY (PictureId) REFERENCES Pictures(Id),
	FOREIGN KEY (UserId) REFERENCES Users(Id),
	FOREIGN KEY (CategoryId) REFERENCES Category(Id)
)

CREATE TABLE BlogComments
(
	Id INT IDENTITY PRIMARY KEY,
	BlogId INT NOT NULL,
	UserId INT NOT NULL,
	Comment TEXT NOT NULL,
	CreateAt DATETIME NOT NULL DEFAULT GETDATE(),
	FOREIGN KEY (BlogId) REFERENCES Blogs(Id),
	FOREIGN KEY (UserId) REFERENCES Users(Id)
)

CREATE TABLE Questions
(
	Id INT IDENTITY PRIMARY KEY,
	UserId INT NOT NULL,
	CategoryId INT NOT NULL,
	Title NVARCHAR(255) NOT NULL,
	Content NTEXT NOT NULL,
	CreateAt DATETIME NOT NULL DEFAULT GETDATE(),
	IsDeleted BIT NOT NULL DEFAULT 0, --True xóa
	FOREIGN KEY (UserId) REFERENCES Users(Id),
	FOREIGN KEY (CategoryId) REFERENCES Category(Id)
)

CREATE TABLE Answers
(
	Id INT IDENTITY PRIMARY KEY,
	QuestionId INT NOT NULL,
	UserId INT NOT NULL,
	Comment TEXT NOT NULL,
	CreateAt DATETIME NOT NULL DEFAULT GETDATE(),
	FOREIGN KEY (QuestionId) REFERENCES Questions(Id),
	FOREIGN KEY (UserId) REFERENCES Users(Id)
)

CREATE TABLE Course
(
	Id INT IDENTITY PRIMARY KEY,
	LecturerId INT NOT NULL,
	CategoryId INT NOT NULL,
	CreateAt DATETIME NOT NULL DEFAULT GETDATE(),
	Title NTEXT NOT NULL,
	PictureId INT DEFAULT 1,
	FOREIGN KEY (PictureId) REFERENCES Pictures(Id),
	FOREIGN KEY (LecturerId) REFERENCES Users(Id),
	FOREIGN KEY (CategoryId) REFERENCES Category(Id)
)

CREATE TABLE WillLearn
(
	Id INT IDENTITY PRIMARY KEY,
	CourseId INT NOT NULL,
	Content NVARCHAR(1000) NOT NULL,
	FOREIGN KEY (CourseId) REFERENCES Course(Id)
)

CREATE TABLE Requirements
(
	Id INT IDENTITY PRIMARY KEY,
	CourseId INT NOT NULL,
	Content NVARCHAR(1000) NOT NULL,
	FOREIGN KEY (CourseId) REFERENCES Course(Id)
)

CREATE TABLE Tracks 
(
	Id INT IDENTITY PRIMARY KEY,
	CourseId INT NOT NULL,
	Title NVARCHAR(255) NOT NULL,
	FOREIGN KEY (CourseId) REFERENCES Course(Id)
)

CREATE TABLE TrackSteps 
(
	Id INT IDENTITY PRIMARY KEY,
	TrackId INT NOT NULL,
	Title NVARCHAR(255) NOT NULL,
	Duration INT NOT NULL,
	FOREIGN KEY (TrackId) REFERENCES Tracks(Id)
)
